### PR TITLE
Hook header controller validate

### PR DESCRIPTION
**Pull request by crashncrow**
- orderopc controller name added to array
- case sensitive getValue

### CODE REVIEW

**Comment by crashncrow** [comment]
Hi! 

I added 'orderopc' to the array because apparently prestashop core checks against that string

https://github.com/PrestaShop/PrestaShop/blob/70d12a5ffbd9f1123e76cded1be8d2f78d5f015c/controllers/front/ParentOrderController.php#L69

Diego

**Comment by clotaire202** [comment]
Ok... we never have return about this. 
We need check why Dispatcher::getInstance()->getController() is or could be different to Tools::getValue('controller');

So should we replace Tools::getValue('controller') by Dispatcher::getInstance()->getController(). It could be better ?

**Comment by clotaire202** [comment]
We fixed Tools::getvalue('controller') by Tools::getValue('controller') to include it on 2.1.1 release.

**Comment by clotaire202** [comment]
@crashncrow 

We found that Prestashop replace - by empty here :
https://github.com/PrestaShop/PrestaShop/blob/1.6.1.24/classes/Dispatcher.php#L806

**Comment by clotaire202** [comment]
Now in conflict but our developper add your code one 2.2.0.

**Pull request closed without merging**
